version: "3.4"

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIROMENT=Development
      - ConnectionString=Server=sql.bsite.net\MSSQL2016;Database=fumlab_db;User Id=fumlab_db;Password=Password12345!;TrustServerCertificate=true;
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=Password_123"
      - "ACCEPT_EULA=Y"
    container_name: mssql
    ports:
      - "1555:1433"
client:
      image: ${DOCKER_REGISTRY-}blazor
      build:
        context: ./BlazorClient
        dockerfile: ./dockerfile
      environment:
        - API_URL=http://webapi:5000
        - CLIENT_ENVIRONMENT=Development
      ports:
        - "3000:80"
      depends_on:
        - webapi