version: "3.4"

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIROMENT=Development
      - ConnectionString="Server=.;Database=FumLab;TrustServerCertificate=True;Trusted_Connection=True";MultipleActiveResultSets = true
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=123"
      - "ACCEPT_EULA=Y"
    container_name: mssql
    ports:
      - "1555:1433"